### ISSUE TITLE
Would love to contribute, have few queries

### ISSUE THREAD

**Issue by subhashdasyam** [evilsocket/nerve#15]
I would like to take the following #TODO

https://github.com/evilsocket/nerve/blob/main/src/agent/namespaces/http/mod.rs#L185

I need more information on what response type and how do you want this to be handled :) 

like json, text/html, text/plain ? 

@evilsocket  @eltociear  @5ibyl

**Comment by evilsocket** [comment]
hey @subhashdasyam that's awesome! thank you so much

the main idea is pretty simple: 

* everything text/* and application/* gets added to the response as it is
* anything else (non textual documents) should NOT be added to the response since the model can't possibly understand it anyway (for now, in the future images could be sent to multimodal LLMs), so the body can be replaced with something like "BINARY DATA" or whatever

thoughts?

**Comment by subhashdasyam** [comment]
Make sense and I agree :-) will submit PR for this soon

**Comment by subhashdasyam** [comment]
@evilsocket please verify the PR :-) if that's what you have in your mind

**Comment by evilsocket** [comment]
merged! thanks @subhashdasyam
